apiVersion: apps/v1
kind: Deployment
metadata:
  name: habitator-api
  labels:
    app: habitator
    name: habitator-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: habitator
      name: habitator-api
  template:
    metadata:
      name: habitator-api
      labels:
        app: habitator
        name: habitator-api
    spec:
      containers:
        - name: habitator-api
          image: {{ .Values.backend.repository }}:{{ .Values.backend.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              port: http
              path: /health/alive
          readinessProbe:
            httpGet:
              port: http
              path: /health
          env:
            - name: OTLP_ENDPOINT_URL
              value: {{ .Values.backend.otelCollectorEndpoint }}
      restartPolicy: Always
      