name: Backend build

on:
  push:
    branches: [ "main" ]
    paths: [ "src/backend/**" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "src/backend/**" ]
  workflow_dispatch:
    
jobs:
  build:
    defaults:
      run:
        working-directory: ./src/backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
  
  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4
      - uses: googleapis/release-please-action@v4
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
