name: Release

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: 
    
    
jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      backend--release-created: ${{ steps.release.outputs.backend--release_created }}
      backend--version: ${{ steps.release.outputs.backend--version }}

    steps:
      - uses: actions/checkout@v4
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          include-component-in-tag: true
      - run:
          echo "${{ toJSON(steps.release.outputs) }}"
        continue-on-error: true
       
  publish-backend-docker-image:
    runs-on: ubuntu-latest
    if: jobs.id.release.outputs.backend--release-created == 'true'
    needs: release
    steps:
      - uses: actions/checkout@v4
      - name: Echo version
        run: |
          echo Pushing mrnustik/habitator-api:v${{ needs.release.outputs.backend--version }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Habitator.API/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: mrnustik/habitator-api:v${{ needs.release.outputs.backend--version }}
          provenance: true
          sbom: true