name: Release

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: 
    
    
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          include-component-in-tag: true
      - run: 
          echo ${{ toJSON(steps.release.outputs) }}
        continue-on-error: true
       